name: "Terraform Plan"
on:
    push:
      branches:
      - main
    pull_request:
      branches:
      - main

env:
    TF_VERSION: 1.1.7
jobs:
  code-scan-deploy:
    name: "Code Scan & Dev deploy"
    runs-on: ubuntu-latest
    environment: 
        name: dev
    defaults:
        run:
          working-directory: ./platform
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config "container_name=${{ vars.SA_CONTAINER }}"

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
            directory: .
            soft_fail: false
            framework: terraform
            skip_check: CKV_TF_1
            download_external_modules: true
            output_file_path: platform/

      - name: Terraform Plan
        id: validate
        run: terraform validate
     
      - name: Terraform Plan
        id: dev-plan
        run: terraform plan -var-file="../environment/${{ vars.ENV }}.tfvars"

      - name: Terraform Apply
        id: dev-apply
        run: terraform apply -var-file="../environment/${{ vars.ENV }}.tfvars" -auto-approve 


  QA-deploy:
    name: "Prod Deploy"
    runs-on: ubuntu-latest
    environment: 
        name: qa
    needs: code-scan-deploy
    defaults:
        run:
            working-directory: ./platform
    env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        id: init
        run: terraform init -backend-config "container_name=${{ vars.SA_CONTAINER }}"

      - name: Terraform Plan
        id: dev-plan
        run: terraform plan -var-file="../environment/${{ vars.ENV }}.tfvars"

      - name: Terraform Apply
        id: qa-apply
        run: terraform apply -var-file="../environment/${{ vars.ENV }}.tfvars" -auto-approve 

  prod-deploy:
    name: "QA Deploy"
    runs-on: ubuntu-latest
    environment: 
        name: prod
    needs: QA-deploy
    defaults:
        run:
            working-directory: ./platform
    env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        id: init
        run: terraform init -backend-config "container_name=${{ vars.SA_CONTAINER }}"

      - name: Terraform Plan
        id: dev-plan
        run: terraform plan -var-file="../environment/${{ vars.ENV }}.tfvars"

      - name: Terraform Apply
        id: qa-apply
        run: terraform apply -var-file="../environment/${{ vars.ENV }}.tfvars" -auto-approve 